### ISSUE TITLE
🐛 [BUG] - On click anywhere plays a paused story

### ISSUE THREAD

**Issue by Gauravdarkslayer** [Gauravdarkslayer/ngx-stories#19]
### Description

When a user pauses a story, clicking anywhere on the screen unintentionally resumes the story playback. This issue causes an unwanted interaction, making it difficult for users to pause and resume stories at their convenience.

Expected Behavior:
After pausing a story, the story should remain paused until the user explicitly interacts with the play button. Clicking elsewhere on the screen should not trigger story playback.

Actual Behavior:
The story resumes playing upon any click interaction, regardless of the element clicked on, creating a disruptive user experience.

### Reproduction steps

```bash
1. Pause a ongoing story
2. Now click anywhere
3. You should see the story starts playing automatically, which should not be the case.
4. And even play button doesn't changed to pause button
```

### Browsers

Chrome Desktop

**Comment by Piyush-Goenka** [comment]
Hey @Gauravdarkslayer 
I’d like to resolve the issue where clicking anywhere on the screen resumes a paused story. The expected behavior is for the story to remain paused until the user explicitly clicks the play button. I’ll work on ensuring that only the play button triggers playback, enhancing user control and experience.
Please assign this issue to me.

**Comment by meetbhalodi11** [comment]
@Gauravdarkslayer I can help here. maybe issue with global even listeners

**Comment by Gauravdarkslayer** [comment]
@meetbhalodi11 Yes may be!
I've assigned this issue to you!

**Comment by Gauravdarkslayer** [comment]
@meetbhalodi11 , can we close this issue ? If it's sorted ?
